# Generated by Django 4.1.7 on 2023-03-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_passengers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flights',
            new_name='Flight',
        ),
        migrations.RenameModel(
            old_name='Passengers',
            new_name='Passenger',
        ),
    ]
